/**
 * src/sdk/grpc/types.ts
 *
 * Re-exports the generated protobuf message types so that callers can import
 * them from a single stable path without depending on the generated file
 * layout directly.
 *
 * Usage:
 *   import type { TrustScore, Bond, Attestation } from './src/sdk/grpc/types.js'
 *
 * NOTE: These types are generated by `buf generate`.  Run that command before
 * importing from this file.
 */

// Trust
export type {
  TrustScore,
  GetTrustScoreRequest,
  GetTrustScoreResponse,
  BatchGetTrustScoresRequest,
  BatchGetTrustScoresResponse,
} from './gen/credence/v1/trust_pb.js'

// Bond
export type {
  Bond,
  GetBondRequest,
  GetBondResponse,
} from './gen/credence/v1/bond_pb.js'

export { BondStatus } from './gen/credence/v1/bond_pb.js'

// Attestation
export type {
  Attestation,
  ListAttestationsRequest,
  ListAttestationsResponse,
  CreateAttestationRequest,
  CreateAttestationResponse,
} from './gen/credence/v1/attestation_pb.js'

// Verification
export type {
  VerificationProof,
  GetVerificationProofRequest,
  GetVerificationProofResponse,
  VerifyProofRequest,
  VerifyProofResponse,
} from './gen/credence/v1/verification_pb.js'

// Governance
export type {
  Dispute,
  SlashRequest,
  SubmitDisputeRequest,
  SubmitDisputeResponse,
  GetDisputeRequest,
  GetDisputeResponse,
  UpdateDisputeStatusRequest,
  UpdateDisputeStatusResponse,
  CreateSlashRequestRequest,
  CreateSlashRequestResponse,
  SubmitVoteRequest,
  SubmitVoteResponse,
  GetSlashRequestRequest,
  GetSlashRequestResponse,
  ListSlashRequestsRequest,
  ListSlashRequestsResponse,
} from './gen/credence/v1/governance_pb.js'

export { DisputeStatus, SlashRequestStatus, VoteChoice } from './gen/credence/v1/governance_pb.js'

// Common
export type {
  PageRequest,
  PageResponse,
  ErrorDetail,
  FieldViolation,
} from './gen/credence/v1/common_pb.js'

export { PrivacyClassification } from './gen/credence/v1/common_pb.js'
