/**
 * AUTO-GENERATED by scripts/generate-sdk-errors.ts — DO NOT EDIT.
 * Regenerate with: npm run generate:sdk-errors
 */

export interface CredenceErrorEnvelope {
  error: string
  code: string
  details?: unknown
}

export interface CredenceErrorOptions {
  cause?: unknown
  rawBody?: string
}

export interface SanitizedErrorCause {
  name?: string
  message?: string
  code?: string
  cause?: SanitizedErrorCause
}

const DEFAULT_MESSAGES = {
  'validation_failed': "Validation failed",
  'field_required': "Required field is missing",
  'invalid_format': "Invalid format",
  'invalid_address': "Invalid address",
  'invalid_type': "Invalid type",
  'unexpected_field': "Unexpected field",
  'value_too_small': "Value is too small",
  'value_too_large': "Value is too large",
  'insufficient_funds': "Insufficient funds",
  'unauthorized': "Unauthorized access",
  'forbidden': "Forbidden access",
  'not_found': "Resource not found",
  'conflict': "Conflict",
  'batch_size_exceeded': "Batch size exceeded",
  'batch_size_too_small': "Batch size too small",
  'rate_limit_exceeded': "Rate limit exceeded",
  'service_unavailable': "Service temporarily unavailable",
  'internal_server_error': "An unexpected internal server error occurred",
  'invalid_input': "Invalid input",
  'sdk_request_timeout': "Request timed out",
  'sdk_network_error': "Network error",
  'sdk_invalid_json': "Invalid JSON response",
  'sdk_unmapped_http': "Unmapped HTTP error response",
} as const

/**
 * Strip stack traces from an Error cause chain before serialization or attachment.
 * Prevents server-side stack traces from leaking through nested causes.
 */
export function sanitizeCauseChain(cause: unknown): SanitizedErrorCause | undefined {
  if (cause == null) return undefined

  if (cause instanceof Error) {
    const sanitized: SanitizedErrorCause = {
      name: cause.name,
      message: cause.message,
    }

    const nodeCode = (cause as Error & { code?: unknown }).code
    if (typeof nodeCode === 'string') {
      sanitized.code = nodeCode
    }

    if (cause.cause != null) {
      sanitized.cause = sanitizeCauseChain(cause.cause)
    }

    return sanitized
  }

  if (typeof cause === 'object') {
    const record = cause as Record<string, unknown>
    const sanitized: SanitizedErrorCause = {}

    if (typeof record.name === 'string') sanitized.name = record.name
    if (typeof record.message === 'string') sanitized.message = record.message
    if (typeof record.code === 'string') sanitized.code = record.code
    if ('cause' in record) sanitized.cause = sanitizeCauseChain(record.cause)

    return Object.keys(sanitized).length > 0 ? sanitized : undefined
  }

  return { message: String(cause) }
}

export class CredenceError extends Error {
  public readonly code: string
  public readonly status: number
  public readonly details?: unknown
  public readonly rawBody?: string

  constructor(
    message: string,
    code: string,
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, {
      cause:
        options?.cause != null ? sanitizeCauseChain(options.cause) : undefined,
    })
    this.name = 'CredenceError'
    this.code = code
    this.status = status
    this.details = details
    this.rawBody = options?.rawBody
  }

  toJSON(): CredenceErrorEnvelope & { status: number; rawBody?: string } {
    return {
      error: this.message,
      code: this.code,
      status: this.status,
      ...(this.details !== undefined ? { details: this.details } : {}),
      ...(this.rawBody !== undefined ? { rawBody: this.rawBody } : {}),
    }
  }
}

export class ValidationFailedCredenceError extends CredenceError {
  static readonly errorCode = 'validation_failed' as const

  constructor(
    message: string = DEFAULT_MESSAGES['validation_failed'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'validation_failed', status, details, options)
    this.name = 'ValidationFailedCredenceError'
  }
}

export class FieldRequiredCredenceError extends CredenceError {
  static readonly errorCode = 'field_required' as const

  constructor(
    message: string = DEFAULT_MESSAGES['field_required'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'field_required', status, details, options)
    this.name = 'FieldRequiredCredenceError'
  }
}

export class InvalidFormatCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_format' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_format'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_format', status, details, options)
    this.name = 'InvalidFormatCredenceError'
  }
}

export class InvalidAddressCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_address' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_address'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_address', status, details, options)
    this.name = 'InvalidAddressCredenceError'
  }
}

export class InvalidTypeCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_type' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_type'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_type', status, details, options)
    this.name = 'InvalidTypeCredenceError'
  }
}

export class UnexpectedFieldCredenceError extends CredenceError {
  static readonly errorCode = 'unexpected_field' as const

  constructor(
    message: string = DEFAULT_MESSAGES['unexpected_field'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'unexpected_field', status, details, options)
    this.name = 'UnexpectedFieldCredenceError'
  }
}

export class ValueTooSmallCredenceError extends CredenceError {
  static readonly errorCode = 'value_too_small' as const

  constructor(
    message: string = DEFAULT_MESSAGES['value_too_small'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'value_too_small', status, details, options)
    this.name = 'ValueTooSmallCredenceError'
  }
}

export class ValueTooLargeCredenceError extends CredenceError {
  static readonly errorCode = 'value_too_large' as const

  constructor(
    message: string = DEFAULT_MESSAGES['value_too_large'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'value_too_large', status, details, options)
    this.name = 'ValueTooLargeCredenceError'
  }
}

export class InsufficientFundsCredenceError extends CredenceError {
  static readonly errorCode = 'insufficient_funds' as const

  constructor(
    message: string = DEFAULT_MESSAGES['insufficient_funds'],
    status: number = 422,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'insufficient_funds', status, details, options)
    this.name = 'InsufficientFundsCredenceError'
  }
}

export class UnauthorizedCredenceError extends CredenceError {
  static readonly errorCode = 'unauthorized' as const

  constructor(
    message: string = DEFAULT_MESSAGES['unauthorized'],
    status: number = 401,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'unauthorized', status, details, options)
    this.name = 'UnauthorizedCredenceError'
  }
}

export class ForbiddenCredenceError extends CredenceError {
  static readonly errorCode = 'forbidden' as const

  constructor(
    message: string = DEFAULT_MESSAGES['forbidden'],
    status: number = 403,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'forbidden', status, details, options)
    this.name = 'ForbiddenCredenceError'
  }
}

export class NotFoundCredenceError extends CredenceError {
  static readonly errorCode = 'not_found' as const

  constructor(
    message: string = DEFAULT_MESSAGES['not_found'],
    status: number = 404,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'not_found', status, details, options)
    this.name = 'NotFoundCredenceError'
  }
}

export class ConflictCredenceError extends CredenceError {
  static readonly errorCode = 'conflict' as const

  constructor(
    message: string = DEFAULT_MESSAGES['conflict'],
    status: number = 409,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'conflict', status, details, options)
    this.name = 'ConflictCredenceError'
  }
}

export class BatchSizeExceededCredenceError extends CredenceError {
  static readonly errorCode = 'batch_size_exceeded' as const

  constructor(
    message: string = DEFAULT_MESSAGES['batch_size_exceeded'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'batch_size_exceeded', status, details, options)
    this.name = 'BatchSizeExceededCredenceError'
  }
}

export class BatchSizeTooSmallCredenceError extends CredenceError {
  static readonly errorCode = 'batch_size_too_small' as const

  constructor(
    message: string = DEFAULT_MESSAGES['batch_size_too_small'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'batch_size_too_small', status, details, options)
    this.name = 'BatchSizeTooSmallCredenceError'
  }
}

export class RateLimitExceededCredenceError extends CredenceError {
  static readonly errorCode = 'rate_limit_exceeded' as const

  constructor(
    message: string = DEFAULT_MESSAGES['rate_limit_exceeded'],
    status: number = 429,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'rate_limit_exceeded', status, details, options)
    this.name = 'RateLimitExceededCredenceError'
  }
}

export class ServiceUnavailableCredenceError extends CredenceError {
  static readonly errorCode = 'service_unavailable' as const

  constructor(
    message: string = DEFAULT_MESSAGES['service_unavailable'],
    status: number = 503,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'service_unavailable', status, details, options)
    this.name = 'ServiceUnavailableCredenceError'
  }
}

export class InternalServerErrorCredenceError extends CredenceError {
  static readonly errorCode = 'internal_server_error' as const

  constructor(
    message: string = DEFAULT_MESSAGES['internal_server_error'],
    status: number = 500,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'internal_server_error', status, details, options)
    this.name = 'InternalServerErrorCredenceError'
  }
}

/**
 * @deprecated Legacy error code. Use `validation_failed` instead.
 */
export class InvalidInputCredenceError extends CredenceError {
  static readonly errorCode = 'invalid_input' as const

  constructor(
    message: string = DEFAULT_MESSAGES['invalid_input'],
    status: number = 400,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'invalid_input', status, details, options)
    this.name = 'InvalidInputCredenceError'
  }
}

export class SdkRequestTimeoutCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_request_timeout' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_request_timeout'],
    status: number = 0,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_request_timeout', status, details, options)
    this.name = 'SdkRequestTimeoutCredenceError'
  }
}

export class SdkNetworkErrorCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_network_error' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_network_error'],
    status: number = 0,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_network_error', status, details, options)
    this.name = 'SdkNetworkErrorCredenceError'
  }
}

export class SdkInvalidJsonCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_invalid_json' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_invalid_json'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_invalid_json', status, details, options)
    this.name = 'SdkInvalidJsonCredenceError'
  }
}

export class SdkUnmappedHttpCredenceError extends CredenceError {
  static readonly errorCode = 'sdk_unmapped_http' as const

  constructor(
    message: string = DEFAULT_MESSAGES['sdk_unmapped_http'],
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, 'sdk_unmapped_http', status, details, options)
    this.name = 'SdkUnmappedHttpCredenceError'
  }
}

export const CREDENCE_ERROR_REGISTRY = {
  'validation_failed': ValidationFailedCredenceError,
  'field_required': FieldRequiredCredenceError,
  'invalid_format': InvalidFormatCredenceError,
  'invalid_address': InvalidAddressCredenceError,
  'invalid_type': InvalidTypeCredenceError,
  'unexpected_field': UnexpectedFieldCredenceError,
  'value_too_small': ValueTooSmallCredenceError,
  'value_too_large': ValueTooLargeCredenceError,
  'insufficient_funds': InsufficientFundsCredenceError,
  'unauthorized': UnauthorizedCredenceError,
  'forbidden': ForbiddenCredenceError,
  'not_found': NotFoundCredenceError,
  'conflict': ConflictCredenceError,
  'batch_size_exceeded': BatchSizeExceededCredenceError,
  'batch_size_too_small': BatchSizeTooSmallCredenceError,
  'rate_limit_exceeded': RateLimitExceededCredenceError,
  'service_unavailable': ServiceUnavailableCredenceError,
  'internal_server_error': InternalServerErrorCredenceError,
  'invalid_input': InvalidInputCredenceError,
  'sdk_request_timeout': SdkRequestTimeoutCredenceError,
  'sdk_network_error': SdkNetworkErrorCredenceError,
  'sdk_invalid_json': SdkInvalidJsonCredenceError,
  'sdk_unmapped_http': SdkUnmappedHttpCredenceError,
} as const satisfies Record<string, typeof CredenceError>

export type CredenceErrorCode = keyof typeof CREDENCE_ERROR_REGISTRY

export const CREDENCE_ERROR_CODES = Object.keys(CREDENCE_ERROR_REGISTRY) as CredenceErrorCode[]

export function isCredenceError(value: unknown): value is CredenceError {
  return value instanceof CredenceError
}

export function parseCredenceErrorEnvelope(body: string): CredenceErrorEnvelope | null {
  try {
    const parsed: unknown = JSON.parse(body)
    if (
      parsed != null &&
      typeof parsed === 'object' &&
      typeof (parsed as Record<string, unknown>).error === 'string' &&
      typeof (parsed as Record<string, unknown>).code === 'string'
    ) {
      const envelope = parsed as CredenceErrorEnvelope
      return {
        error: envelope.error,
        code: envelope.code,
        ...(envelope.details !== undefined ? { details: envelope.details } : {}),
      }
    }
  } catch {
    return null
  }
  return null
}

export function createCredenceErrorFromEnvelope(
  envelope: CredenceErrorEnvelope,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[envelope.code as CredenceErrorCode]
  if (Ctor) {
    return new Ctor(envelope.error, status, envelope.details, options)
  }

  return new SdkUnmappedHttpCredenceError(
    envelope.error,
    status,
    envelope.details,
    options,
  )
}

export function createTransportCredenceError(
  code: Extract<
    CredenceErrorCode,
    'sdk_request_timeout' | 'sdk_network_error' | 'sdk_invalid_json' | 'sdk_unmapped_http'
  >,
  message: string,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[code]
  return new Ctor(message, status, undefined, options)
}
