export { CredenceClient, CredenceError } from './client.js'
export {
  CredenceConfig,
  CredenceApiError,
  TrustScore,
  BondStatus,
  Attestation,
  AttestationsResponse,
  VerificationProof,
} from './types.js'
export {
  CredenceErrorEnvelope,
  CredenceErrorOptions,
  SanitizedErrorCause,
  CREDENCE_ERROR_REGISTRY,
  CREDENCE_ERROR_CODES,
  CredenceErrorCode,
  createCredenceErrorFromEnvelope,
  createTransportCredenceError,
  parseCredenceErrorEnvelope,
  sanitizeCauseChain,
  isCredenceError,
  ValidationFailedCredenceError,
  FieldRequiredCredenceError,
  InvalidFormatCredenceError,
  InvalidAddressCredenceError,
  InvalidTypeCredenceError,
  UnexpectedFieldCredenceError,
  ValueTooSmallCredenceError,
  ValueTooLargeCredenceError,
  InsufficientFundsCredenceError,
  UnauthorizedCredenceError,
  ForbiddenCredenceError,
  NotFoundCredenceError,
  ConflictCredenceError,
  BatchSizeExceededCredenceError,
  BatchSizeTooSmallCredenceError,
  RateLimitExceededCredenceError,
  ServiceUnavailableCredenceError,
  InternalServerErrorCredenceError,
  InvalidInputCredenceError,
  SdkRequestTimeoutCredenceError,
  SdkNetworkErrorCredenceError,
  SdkInvalidJsonCredenceError,
  SdkUnmappedHttpCredenceError,
} from './errors.generated.js'
