import { z } from './openapi.js'

/**
 * Zod schema for a Wallet record returned from the database layer.
 */
export const walletSchema = z
  .object({
    id: z.string().uuid().openapi({
      description: 'Wallet UUID (auto-generated by Postgres)',
      example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
    }),
    address: z.string().min(1).openapi({
      description: 'Blockchain wallet address',
      example: '0xTestAddress1',
    }),
    balance: z.string().openapi({
      description: 'Current balance as a decimal string (NUMERIC(36,18))',
      example: '100.000000000000000000',
    }),
    currency: z.string().openapi({
      description: 'Currency code',
      example: 'USD',
    }),
    createdAt: z.date().openapi({
      description: 'UTC timestamp when the wallet was created',
    }),
    updatedAt: z.date().openapi({
      description: 'UTC timestamp of the last balance change',
    }),
  })
  .openapi('Wallet')

/**
 * Request body for POST /api/wallets — create a new wallet.
 */
export const createWalletBodySchema = z
  .object({
    address: z.string().min(1).openapi({
      description: 'Blockchain wallet address (must be unique)',
      example: '0xNewAddress',
    }),
    initialBalance: z.string().optional().openapi({
      description: 'Optional initial balance as a decimal string. Defaults to "0".',
      example: '50',
    }),
    currency: z.string().optional().openapi({
      description: 'Currency code. Defaults to "USD".',
      example: 'USD',
    }),
  })
  .openapi('CreateWalletBody')

/**
 * Request body for POST /api/wallets/:id/debit
 */
export const walletDebitBodySchema = z
  .object({
    amount: z.string().min(1).openapi({
      description: 'Positive decimal string amount to deduct from the wallet balance.',
      example: '25.50',
    }),
  })
  .openapi('WalletDebitBody')

/**
 * Response returned by the debit operation.
 */
export const walletDebitResponseSchema = z
  .object({
    wallet: walletSchema,
    previousBalance: z.string().openapi({
      description: 'Wallet balance before the debit',
      example: '100.000000000000000000',
    }),
    newBalance: z.string().openapi({
      description: 'Wallet balance after the debit',
      example: '74.500000000000000000',
    }),
    debitedAmount: z.string().openapi({
      description: 'Amount that was debited',
      example: '25.50',
    }),
  })
  .openapi('WalletDebitResponse')

/**
 * Standard wallet error response.
 */
export const walletErrorSchema = z
  .object({
    error: z.string().openapi({ example: 'Wallet abc not found' }),
  })
  .openapi('WalletError')

export type WalletResponse = z.infer<typeof walletSchema>
export type CreateWalletBody = z.infer<typeof createWalletBodySchema>
export type WalletDebitBody = z.infer<typeof walletDebitBodySchema>
export type WalletDebitResponse = z.infer<typeof walletDebitResponseSchema>
