import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  ERROR_CATALOG,
  ERROR_CODE_DEPRECATIONS,
  ERROR_LOCALIZATION_CATALOG,
  type ErrorCatalogEntry,
} from '../src/lib/errorCatalog.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.resolve(__dirname, '../docs/error-codes.md')

const escapeMarkdown = (value: string): string => value.replace(/\|/g, '\\|')

const formatEntryRow = (entry: ErrorCatalogEntry): string => [
  `\`${entry.code}\``,
  String(entry.httpStatus),
  entry.category,
  escapeMarkdown(entry.defaultMessage),
].join(' | ')

const activeEntries = Object.values(ERROR_CATALOG).sort((a, b) => {
  if (a.category !== b.category) return a.category.localeCompare(b.category)
  if (a.httpStatus !== b.httpStatus) return a.httpStatus - b.httpStatus
  return a.code.localeCompare(b.code)
})

const deprecatedEntries = Object.values(ERROR_CODE_DEPRECATIONS).sort((a, b) =>
  a.code.localeCompare(b.code)
)

const localizationRows = Object.entries(ERROR_LOCALIZATION_CATALOG).map(([locale, messages]) => {
  const count = Object.keys(messages).length
  return `| \`${locale}\` | ${count} messages | Catalog default messages for active codes. |`
})

const lines: string[] = [
  '<!-- This file is generated by scripts/generate-error-docs.ts. Do not edit manually. -->',
  '',
  '# Credence API Error Codes',
  '',
  'This reference is generated from `src/lib/errorCatalog.ts` and is the source of truth for machine-readable API error codes.',
  '',
  '## Stability contract',
  '',
  '- Error-code strings are stable public API values. Consumers may safely branch on `code` (and the `error_code` alias where present).',
  '- New codes may be added in minor releases.',
  '- Existing codes must not be removed or renamed without adding a deprecation entry in `ERROR_CODE_DEPRECATIONS`.',
  '- HTTP statuses, categories, and default messages are catalog-managed so handlers do not invent uncatalogued responses.',
  '- Production responses use catalog default messages and omit details to avoid leaking PII, stack traces, or chained error internals.',
  '',
  '## Active codes',
  '',
  '| Code | HTTP status | Category | Default message |',
  '| --- | ---: | --- | --- |',
  ...activeEntries.map((entry) => `| ${formatEntryRow(entry)} |`),
  '',
  '## Localization catalog',
  '',
  '`ERROR_LOCALIZATION_CATALOG` currently ships default English (`en`) messages keyed by error code. Add locales in the catalog before returning localized production responses.',
  '',
  '| Locale | Coverage | Notes |',
  '| --- | ---: | --- |',
  ...localizationRows,
  '',
  '## Deprecated codes',
  '',
]

if (deprecatedEntries.length === 0) {
  lines.push('No error codes are currently deprecated.', '')
} else {
  lines.push(
    '| Code | Deprecated since | Replacement | Reason |',
    '| --- | --- | --- | --- |',
    ...deprecatedEntries.map((entry) => {
      const replacement = entry.replacement ? `\`${entry.replacement}\`` : 'None'
      return `| \`${entry.code}\` | ${entry.deprecatedSince} | ${replacement} | ${escapeMarkdown(entry.reason)} |`
    }),
    ''
  )
}

fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, `${lines.join('\n')}\n`, 'utf-8')
console.log(`Error-code reference generated at ${path.relative(path.resolve(__dirname, '..'), outputPath)}`)
