import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  ERROR_CATALOG,
  ERROR_CATALOG_CODES,
  type ErrorCatalogEntry,
} from '../src/lib/errorCatalog.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.resolve(__dirname, '../src/sdk/errors.generated.ts')

function buildClassBlock(entry: ErrorCatalogEntry): string {
  const lines: string[] = []

  if (entry.deprecated) {
    const replacement = entry.replacedBy
      ? ` Use \`${entry.replacedBy}\` instead.`
      : ''
    lines.push('/**')
    lines.push(` * @deprecated Legacy error code.${replacement}`)
    lines.push(' */')
  }

  lines.push(`export class ${entry.sdkClassName} extends CredenceError {`)
  lines.push(`  static readonly errorCode = '${entry.code}' as const`)
  lines.push('')
  lines.push('  constructor(')
  lines.push('    message: string = DEFAULT_MESSAGES[\'' + entry.code + '\'],')
  if (entry.httpStatus === null) {
    lines.push('    status: number,')
  } else {
    lines.push(`    status: number = ${entry.httpStatus},`)
  }
  lines.push('    details?: unknown,')
  lines.push('    options?: CredenceErrorOptions,')
  lines.push('  ) {')
  lines.push(`    super(message, '${entry.code}', status, details, options)`)
  lines.push(`    this.name = '${entry.sdkClassName}'`)
  lines.push('  }')
  lines.push('}')

  return lines.join('\n')
}

function generate(): string {
  const defaultMessages = ERROR_CATALOG_CODES.map(
    (key) => `  '${ERROR_CATALOG[key].code}': ${JSON.stringify(ERROR_CATALOG[key].defaultMessage)},`,
  ).join('\n')

  const classBlocks = ERROR_CATALOG_CODES.map((key) =>
    buildClassBlock(ERROR_CATALOG[key]),
  ).join('\n\n')

  const registryEntries = ERROR_CATALOG_CODES.map((key) => {
    const entry = ERROR_CATALOG[key]
    return `  '${entry.code}': ${entry.sdkClassName},`
  }).join('\n')

  return `/**
 * AUTO-GENERATED by scripts/generate-sdk-errors.ts — DO NOT EDIT.
 * Regenerate with: npm run generate:sdk-errors
 */

export interface CredenceErrorEnvelope {
  error: string
  code: string
  details?: unknown
}

export interface CredenceErrorOptions {
  cause?: unknown
  rawBody?: string
}

export interface SanitizedErrorCause {
  name?: string
  message?: string
  code?: string
  cause?: SanitizedErrorCause
}

const DEFAULT_MESSAGES = {
${defaultMessages}
} as const

/**
 * Strip stack traces from an Error cause chain before serialization or attachment.
 * Prevents server-side stack traces from leaking through nested causes.
 */
export function sanitizeCauseChain(cause: unknown): SanitizedErrorCause | undefined {
  if (cause == null) return undefined

  if (cause instanceof Error) {
    const sanitized: SanitizedErrorCause = {
      name: cause.name,
      message: cause.message,
    }

    const nodeCode = (cause as Error & { code?: unknown }).code
    if (typeof nodeCode === 'string') {
      sanitized.code = nodeCode
    }

    if (cause.cause != null) {
      sanitized.cause = sanitizeCauseChain(cause.cause)
    }

    return sanitized
  }

  if (typeof cause === 'object') {
    const record = cause as Record<string, unknown>
    const sanitized: SanitizedErrorCause = {}

    if (typeof record.name === 'string') sanitized.name = record.name
    if (typeof record.message === 'string') sanitized.message = record.message
    if (typeof record.code === 'string') sanitized.code = record.code
    if ('cause' in record) sanitized.cause = sanitizeCauseChain(record.cause)

    return Object.keys(sanitized).length > 0 ? sanitized : undefined
  }

  return { message: String(cause) }
}

export class CredenceError extends Error {
  public readonly code: string
  public readonly status: number
  public readonly details?: unknown
  public readonly rawBody?: string

  constructor(
    message: string,
    code: string,
    status: number,
    details?: unknown,
    options?: CredenceErrorOptions,
  ) {
    super(message, {
      cause:
        options?.cause != null ? sanitizeCauseChain(options.cause) : undefined,
    })
    this.name = 'CredenceError'
    this.code = code
    this.status = status
    this.details = details
    this.rawBody = options?.rawBody
  }

  toJSON(): CredenceErrorEnvelope & { status: number; rawBody?: string } {
    return {
      error: this.message,
      code: this.code,
      status: this.status,
      ...(this.details !== undefined ? { details: this.details } : {}),
      ...(this.rawBody !== undefined ? { rawBody: this.rawBody } : {}),
    }
  }
}

${classBlocks}

export const CREDENCE_ERROR_REGISTRY = {
${registryEntries}
} as const satisfies Record<string, typeof CredenceError>

export type CredenceErrorCode = keyof typeof CREDENCE_ERROR_REGISTRY

export const CREDENCE_ERROR_CODES = Object.keys(CREDENCE_ERROR_REGISTRY) as CredenceErrorCode[]

export function isCredenceError(value: unknown): value is CredenceError {
  return value instanceof CredenceError
}

export function parseCredenceErrorEnvelope(body: string): CredenceErrorEnvelope | null {
  try {
    const parsed: unknown = JSON.parse(body)
    if (
      parsed != null &&
      typeof parsed === 'object' &&
      typeof (parsed as Record<string, unknown>).error === 'string' &&
      typeof (parsed as Record<string, unknown>).code === 'string'
    ) {
      const envelope = parsed as CredenceErrorEnvelope
      return {
        error: envelope.error,
        code: envelope.code,
        ...(envelope.details !== undefined ? { details: envelope.details } : {}),
      }
    }
  } catch {
    return null
  }
  return null
}

export function createCredenceErrorFromEnvelope(
  envelope: CredenceErrorEnvelope,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[envelope.code as CredenceErrorCode]
  if (Ctor) {
    return new Ctor(envelope.error, status, envelope.details, options)
  }

  return new SdkUnmappedHttpCredenceError(
    envelope.error,
    status,
    envelope.details,
    options,
  )
}

export function createTransportCredenceError(
  code: Extract<
    CredenceErrorCode,
    'sdk_request_timeout' | 'sdk_network_error' | 'sdk_invalid_json' | 'sdk_unmapped_http'
  >,
  message: string,
  status: number,
  options?: CredenceErrorOptions,
): CredenceError {
  const Ctor = CREDENCE_ERROR_REGISTRY[code]
  return new Ctor(message, status, undefined, options)
}
`
}

const contents = generate()
fs.mkdirSync(path.dirname(outputPath), { recursive: true })
fs.writeFileSync(outputPath, contents, 'utf-8')
console.log(`SDK error classes generated at ${path.relative(process.cwd(), outputPath)}`)
