name: Secret Scanning

on:
  schedule:
    - cron: '0 0 * * 0' # weekly at midnight Sunday
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch full history
      - name: Install Gitleaks
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/download/v8.19.0/gitleaks-linux-amd64 -o gitleaks && chmod +x gitleaks
      - name: Run Gitleaks scan
        env:
          GITLEAKS_CONFIG: .gitleaks.toml
        run: |
          ./gitleaks detect --source . --config=$GITLEAKS_CONFIG --redact --report-path=gitleaks-report.json || true
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks-report.json
